min_sensor_dist: 0.1
self_see_default_padding: 0.10
self_see_default_scale: 1.0
self_see_links:
- name: base_link
- name: pelvis
- name: utorso
- name: waist
- name: l_arm_elbow
- name: l_arm_shoulder_pitch
- name: l_arm_shoulder_roll
- name: l_arm_shoulder_yaw
- name: l_arm_wrist_roll
- name: l_arm_wrist_yaw
- name: l_f0_link_0
- name: l_f1_link_0
- name: l_hand
- name: l_palm
- name: r_arm_elbow
- name: r_arm_shoulder_pitch
- name: r_arm_shoulder_roll
- name: r_arm_shoulder_yaw
- name: r_arm_wrist_roll
- name: r_arm_wrist_yaw
- name: r_f0_link_0
- name: r_f1_link_0
- name: r_hand
- name: r_palm
- name: left_front_flipper_base_link
- name: left_rear_flipper_base_link
- name: right_front_flipper_base_link
- name: right_rear_flipper_base_link


