# VT Sim Hands --------------------------------------------------
  right_hand_traj_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - r_f0_j0
      - r_f1_j0

    gains: # Required because we're controlling an effort interface
      r_f0_j0: {p: &kp_default 100,  d: &kd_default 0.0, i: &ki_default 0, i_clamp: &ki__clamp_default 0}
      r_f1_j0: {p: *kp_default,  d: *kd_default, i: *ki_default, i_clamp: *ki__clamp_default}


    constraints:
      goal_time: &goal_time_constraint 4.0
      r_f0_j0:
        goal: &goal_pos_constraint 0.5
      r_f1_j0:
        goal: *goal_pos_constraint

    stop_trajectory_duration: 0.0
