# VT Hand --------------------------------------------------
right_hand_traj_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - r_f0_j0
      - r_f1_j0

    constraints:
      goal_time: &goal_time_constraint 0.4
      stopped_velocity_tolerance: 1.0
      r_f0_j0:
        goal: &goal_pos_constraint 0.5
        trajectory: &trajectory_pos_constraint 1.0
      r_f1_j0:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint
