# VT Hand --------------------------------------------------
  left_hand_traj_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - l_f0_j0
      - l_f1_j0
      
    constraints:
      goal_time: &goal_time_constraint 4.0
      stopped_velocity_tolerance: 1.0
      l_f0_j0:
        goal: &goal_pos_constraint 0.5
        trajectory: &trajectory_pos_constraint 1.0
      l_f1_j0:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint
