#iBUFFALO-BSGP1601 controller axis numbers and buttun numbers in the joy topics.
---
#velorosity
speedAxis     : 1
turnAxis      : 0
#maxSpeed      : 0.5
#maxTurnW      : 1.570796327
#flipper.fr
frUpButton    : 9
frDownButton  : 7
#frW           : 0.314
#frDefaultAngle: 0.785398163
#flipper.fl
flUpButton    : 8
flDownButton  : 6
#flW           : 0.314
#flDefaultAngle: 0.785398163
#flipper.rr
rrUpButton    : 13
rrDownButton  : 15
#rrW           : 0.314
#rrDefaultAngle: 0.785398163
#flipper.rl
rlUpButton    : 12
rlDownButton  : 14
#rlW           : 0.314
#rlDefaultAngle: 0.785398163
...
